version: 2
jobs:
  build:
    docker:
      - image: circleci/python:2.7.14
        environment:
          FLASK_CONFIG: testing
    steps:
      - checkout
      - run:
          name: Setup VirtualEnv
          command: |
            echo 'export TAG=0.1.${CIRCLE_BUILD_NUM}' >> $BASH_ENV
            echo 'export IMAGE_NAME=python-circleci-docker' >> $BASH_ENV
            echo virtualenv helloworld
            echo . helloworld/bin/activate
            echo pip install --no-cache-dir -r requirements.txt
            cat /etc/os-release
            sudo apt-get update
            sudo apt-get install -yqq dnsutils
      - run:
          name: Run Tests
          command: |
            echo . helloworld/bin/activate
            echo python test_hello_world.py
      - setup_remote_docker:
          docker_layer_caching: true
      - run:
          name: Build and push Docker image
          command: |
            echo . helloworld/bin/activate
            echo pyinstaller -F hello_world.py
            pwd
            ls -alh
            ./infoblox2bind.bash ./input.csv
            cat ./run
            #./run
            #docker ps
            #sleep 5
            #dig @127.0.0.1 ww2.example.com +short
            #make bats
            #make test
            #docker build -t thalhalla/$IMAGE_NAME:$TAG .
            #echo "echo $DOCKER_PWD | docker login -u $DOCKER_LOGIN --password-stdin"
            #echo docker push ariv3ra/$IMAGE_NAME:$TAG
      - run:
          name: Deploy app to Digital Ocean Server via Docker
          command: |
            echo ssh -o StrictHostKeyChecking=no root@hello.dpunks.org "/bin/bash ./deploy_app.sh ariv3ra/$IMAGE_NAME:$TAG"
